package com.wfms.util;

public class Constants {
	public final static String ADD = "add";
	public final static String EDIT = "edit";
	public final static String DELETE = "delete";
	public final static String UPDATE = "update";
	public final static String VIEW = "view";
	public final static String ACTION = "action";
	public final static String DETAIL = "detail";
	public final static String LOGIN = "login";
	public final static String LOGOUT = "logout";
	public final static String ASSIGN_TASK = "assign_task";
	public final static String MY_TASK = "my_task";
	public final static String ASSIGN = "assign";
	public final static String UPDATE_TASK_STATUS = "update_task_status";
	public final static int ACTIVE = 1;
	public final static int OPEN = 1;
	public final static int IN_PROGRESS = 2;
	public final static int CLOSED = 3;
	public final static int BLOCKED = 4;
	public final static int DEACTIVE = 0;
	public final static String COMPOSE = "compose";
	public final static String BY_DESIGNATION = "by_designation";
	public final static String GET_RESOURCES = "get_resources";
	public final static String ADD_RESOURCE = "add_resource";
	public final static String EXISTS = "exists";
	public final static String ADMIN = "admin";
	public final static String USERNAME = "username";
	public final static String PASSWORD = "password";
	public final static String DEFAULT_PASSWORD = "wfms@123";
	public final static String AT = "@";
	public final static String DOMAIN_NAME = "wfms.com";
	public final static String CHANGE_PASSWORD = "changePassword";
	public final static String GET_STATE_LIST = "getStateList";
	public final static String GET_CITY_LIST = "getCityList";
	public final static String CHANGE_STATUS = "changeStatus";
	public final static String TRUE = "true";
	public final static String FALSE = "false";
	public final static String COUNTRY_EXISTS = "countryExists";
	// constants for messages
	public final static String INBOX = "inbox";
	public final static String SENT = "sent";
	public final static String INBOX_DELETE = "inbox_delete";
	public final static String SENT_DELETE = "sent_delete";
	public final static int READ = 1;
	public final static int UNREAD = -1;
	public final static int FROM_HAS_NOT_DELETED_SENT_MSG = 1;
	public final static int FROM_HAS_DELETED_SENT_MSG = -1;
	public final static int TO_HAS_NOT_DELETED_RECEIVED_MSG = 1;
	public final static int TO_HAS_DELETED_RECEIVED_MSG = -1;
	public final static int TRASHED = -1;
	public final static String WELCOME_SUBJECT = "Welcome to WFMS";
	public static final String GREETING = "Greetings from WFMS.<br>";
	public static final String SINGLE_LINE_BREAK = "<br><br>";
	public static final String HI = "Hi";
	public static final String COMMA = ",";
	public static final String COLLON = ":";
	public static final String DOUBLE_QUOTE = "\"\"";
	public static final String SELECT = "select";
	public static final String THANKS = "Thanks";
	public static final String SIGNATURE = "WFMS team";
	public static final String USERNAME_PASSWORD_TEXT = "Please find below your username and password. Please update your password after first login.<BR><BR>";
	public static final String REGISTER_MSG = "Thank you for joining WFMS.<br><br>";
	public static final String FOR_QUERIES_MSG = "For any queries, mail us at info@wfms.com<br><br>";
	public static final String DETAILS_SAVED_SUCCESSFULLY = "details saved successfully";
	
}
